config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }

  resources :products do
    resources :comments
  end


  get 'simple_pages/products'
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/index'
  get 'simple_pages/landing_page' #, to: 'products#index'
    root to: 'simple_pages#landing_page'
  post 'simple_pages/thank_you'
  post 'payments/create'

  resources :users
  resources :orders, only: [:index, :show, :create, :destroy]

  mount ActionCable.server => '/cable'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :comments
  has_many :orders

    validates :name, presence: true

    def self.search(search_term)
      Product.where("name LIKE ?", "%#{search_term}%")
      if Rails.env.development?
        Product.where("name LIKE ? OR description LIKE ? OR color LIKE ?", "%#{search_term}%", "%#{search_term}%", "%#{search_term}%")
      else
        Product.where("name ilike ? OR description ilike ? OR color ilike ?", "%#{search_term}%", "%#{search_term}%", "%#{search_term}%")
      end
    end

    def index
      if params[:q]
        search_term = params[:q]
        @products = Product.search(search_term)
      else
        @products = Product.all
      end
    end

    def highest_rating_comment
      comments.rating_desc.first
    end

    def lowest_rating_comment
      comments.rating_asc.first
    end

    def average_rating
      comments.average(:rating).to_f
    end


end

# SQL Databases:
# LIKE is sqlites3
# ilike is postgres

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      @products = Product.search(search_term)
      if @products.nil?
          flash.now[:success] = "We're sorry, we don't have anything related to #{search_term}. Please check out the other products that we offer."
      end
    # return our filtered list here
    else
      @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
  end

  # GET /products/new
  def new
  #  byebug use byebug (gem) to set breakpoints and step through live code in Rails.
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to "/simple_pages/landing_page", notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :color, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = @products
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
<div class="product-reviews" >
    <% @comments.each do |comment| %>
      <%= render comment %>
    <% end %>
</div><!-- end product-reviews div-->

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %> <!-- generates form tags -->
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %><!-- generates label tags -->
    <%= form.text_field :name %> <!-- generates input tags -->
  </div>

  <div class="field">
    <%= form.label :description %> <!-- generates label tags -->
    <%= form.text_area :description %><!-- generates input tags -->
  </div>

  <div class="field">
    <%= form.label :image_url %><!-- generates label tags -->
    <%= form.text_field :image_url %><!-- generates input tags -->
  </div>

  <div class="field">
    <%= form.label :color %><br><!-- generates label tags -->
    <%= form.text_field :color %><!-- generates input tags -->
  </div>

  <div class="field">
    <%= form.label :price %><br><!-- generates label tags -->
    <%= form.text_field :price %><!-- generates input tags -->
  </div>

  <div class="actions">
    <%= form.submit %> <!-- generates submit button tags -->
  </div>
<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>


    <h4>Add a review:</h4>
    <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
      <p>
        <%= f.label :body, "Comments" %>
        <%= f.text_area :body, class: "comment_body" %>
      </p>
      <p>
        <div class="rating"></div>
      </p>
      <p class="review-submit">
        <%= f.submit "Submit" %>
      </p>
    <% end %>

<% end %>

app/views/products/_product.html.erb
<div class="col-lg col-md-4 col-xs-12">
    <% cache product do %>

      <%= link_to product do %><br>
        <h4><%= product.name %></h4>
            <%= image_tag(product.image_url, class: "img-fluid") %>
      <% end %><br>
        <p>
          <%= product.description %><br>
          Price:
          <%= product.price %>
        </p>

        <div class="product-btn">
            <%= link_to 'Show', product, class:'btn btn-outline-success' %>
            <%= link_to 'Edit', edit_product_path(product), class: 'btn btn-outline-info', id: 'edit-btn' %>
            <%= link_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-warning' %>
        </div>

    <% end %> <!--cache end-->


</div><!-- /col -->

app/views/products/edit.html.erb
<h4>Editing Product</h4>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h2 id="prod-title">Products</h2>

<div class="container-fluid", id="products-page">
  <div class="row col-md-3 col-lg-12">
    <% cache(cache_key_for_products) do %>
      <%= render @products %>
    <% end %>
  </div><!-- end row div-->
</div><!-- end container-fluid div-->

<br>

<% if signed_in? && current_user.admin? %>
    <div class="btn btn-outline-primary">
      <a class="new-product" href="/products/new">New Product</a>
    </div> <!-- end btn div -->
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<!-- Use this (@product.comments.order(rating: :desc).first.body) in order to see highest rating comment first with < % = -->
<h3><%= @product.name %></h3>

  <div class="container", id="products-show-page">
    <div class="product-image img-responsive">
      <%= image_tag(@product.image_url, class: "image-fluid img-zoom", data_zoom_image: "@product.image_url") %>
    </div>

      <div class="caption">
        <p><%= @product.description %><br>Color:<%= @product.color %></p>
          Average Rating:
        <div class="rated", id="#average-rating" data-score="<%= @product.average_rating %>"></div> <br>
      </div><!--end caption div-->

      <div class="">
        <%= form_with(url:"/payments/create", method: "post", local: true) do |form| %>
          <%= render partial: "shared/stripe_checkout_button" %>
          <%= hidden_field_tag(:product_id, @product.id) %>
        <% end %>
      </div><br><!--end stripe payment div-->
  </div> <!--end container div-->


  <div class="container"">

      <div class="row" data-product-id="<%= @product.id %>">
        <div class="col-md", id="thumbnail-row">
          <div class="products-cmts", id="product-cmts" >
            <h6><em>Your Comments here:<em></h6>
            <div class="alert alert-info" style="display:none" role="alert">A new comment was posted!
            </div>
              <%= render 'comments' %>
              <%= will_paginate @comments, :page_links => false %>
          </div> <!--end products-cmts div-->
        </div> <!--end col div-->


        <div class="col-md", id="review-row" >
          <%= render 'new_comment' %>
        </div>
      </div> <!--end row div-->
    </div> <!--end container div-->

    <div class="buttons">
      <p><%= link_to 'Edit', edit_product_path(@product) %> |
      <%= link_to 'Back', products_path %></p>
    </div><!--end buttons div-->