config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }

  resources :products do
    resources :comments
  end


  get 'simple_pages/products'
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/index'
  get 'simple_pages/landing_page' #, to: 'products#index'
    root to: 'simple_pages#landing_page'
  post 'simple_pages/thank_you'
  post 'payments/create'

  resources :users
  resources :orders, only: [:index, :show, :create, :destroy]

  mount ActionCable.server => '/cable'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Riding-Vintage | Online Bike Store</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
    integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
    integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
    integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Ruthie" rel="stylesheet" type="text/css">

    <link href="https://fonts.googleapis.com/css?family=Sail" rel="stylesheet" type="text/css">

    <link href="https://fonts.googleapis.com/css?family=Charmonman" rel="stylesheet" type="text/css">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Bilbo" rel="stylesheet" type="text/css">

    <link href="https://fonts.googleapis.com/css?family=Kristi" rel="stylesheet" type="text/css">



  </head>

    <% if alert %>
      <p id="alert" class="alert alert-secondary`"><%= alert %></p>
    <% end %>

    <% if notice %>
      <p id="notice" class="alert alert-primary"><%= notice %></p>
    <% end %>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to simple_pages_landing_page_path, class: 'navbar-brand' do %>
        Riding-Vintage
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
          <button type="button" class="btn btn-light">
            <li class="nav-item active">
              <%= link_to "Home", simple_pages_landing_page_path, class: "nav-link" %><span class="sr-only">(current)</span>
            </li>
          </button>

          <button type="button" class="btn btn-light">
            <li class="nav-item">
              <%= link_to "About", simple_pages_about_path, class: "nav-link" %>
            </li>
          </button>

          <button type="button" class="btn btn-light">
            <li class="nav-item">
              <%= link_to "Products", products_path, class: "nav-link" %>
            </li>
          </button>

          <button type="button" class="btn btn-light">
            <li class="nav-item">
              <%= link_to "Orders", orders_path, class: "nav-link" %>
            </li>
          </button>

          <button type="button" class="btn btn-light">
            <li class="nav-item">
              <%= link_to "Contact", simple_pages_contact_path, class: "nav-link" %>
            </li>
          </button>

          <button type="button" class="btn btn-light">
              <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %>
            </li>
              <% else %>
            <li class="nav-item">
              <%= link_to('Login', new_user_session_path, class: "nav-link") %>
            </li>
              <% end %>
          </button>
        </ul>
            <%= form_with(url: products_path, method: 'get', local: true) do |form| %>
              <%= form.text_field :q, id: 'q', value: params[:q], class: "form-inline-block", placeholder: "Search here..." %>
              <%= form.submit 'Search', class: 'btn btn-submit my-sm-2', id: 'submit-btn' %>
            <% end %>
      </div><!--end of NavbarNav div-->
    </nav><!--end navbar-expand-lg nav-->

    <%= yield %>

  </body>

  <footer>
    <%= image_tag("divider-line.png", id: "footer-img") %> <br />
     &copy; 2018 Vintage Bikes
  </footer>

</html>

<!--HTML EQUIVALENT FOR SEARCH BAR =
<form action="/products" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="✓">
    <label for="q">Search for:</label>
    <input id="q" type="text" name="q">
    <input type="submit" name="commit" value="Search" data-disable-with="Search">
</form> -->

<!-- Same as rails block above
  <a class="navbar-brand" href="#">
    <img id="brand-img" src="http://www.drodd.com/images15/letter-r17.jpg" class="d-inline-block align-top" alt="">
      iding-Vintage
  </a>
  -->